# action.yml
name: 'Release Version Generator'
description: 'Generates the next release version for a Git repository, given the set of existing tags and various settings'
inputs:
  versionScheme: 
    description: 'The version scheme, defaults to "0.0.x"'
    required: false
    default: '0.0.x'
  versionSchemes: 
    description: 'The multiple version schemes to calculate for, comma delimitered. Empty by default (since v3)"'
    required: false
    default: ''
  tagPrefix:
    description: 'The prefix characters for each corresponding repository tag, defaults. to "v"'
    required: false
    default: 'v'
  placeholderChars:
    description: 'The placeholder char (or characters) representing the incrementing version number within the scheme, defaults to "x"'
    required: false
    default: 'x'
  workingDirectory:
    description: 'The working directory for the assessment'
    required: false
    default: '.'
  format:
    description: 'The output format, defaults to plain text (if empty). Supported options are <empty> and "json"'
    required: false
    default: ''
outputs:
  nextVersion: 
    description: 'The next version number based on the existing tags.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TAG_PREFIX: ${{ inputs.tagPrefix }}
    VERSION_SCHEME: ${{ inputs.versionScheme }}
    VERSION_SCHEMES: ${{ inputs.versionSchemes }}
    PLACEHOLDER_CHARS: ${{ inputs.placeholderChars }}
    FORMAT: ${{ inputs.format }}
