name: 'Master build'

on:
  push:
    branches:
      - 'main'
      - 'feature/**'

run-name: 'Master build #${{github.run_number}}'

env:
  NODE_VERSION: '18.12.1'

jobs:
  build:

    runs-on: ubuntu-latest

    outputs:
      imageTags: ${{ steps.nextVersions.outputs.nextVersions }}

    steps:
      - 
        name: Checkout the branch
        uses: actions/checkout@v3
      - 
        name: Get tags
        run: git fetch --tags origin
      - 
        name: Setup Node
        uses: actions/setup-node@v3

        with:
          node-version: ${{ env.NODE_VERSION }}
      - 
        name: Install Node modules
        run: cd app/ && npm install
      - 
        name: Test
        run: cd app/ && npm run checks && npm test
      - 
        name: Determine next versions
        id: nextVersions
        uses: newsome-solutions-ltd/release-version-action@feature/multiple-versions
        with:
          versionSchemes: 'feature-x,feature-latest'
          format: 'json'

  tag:

    runs-on: ubuntu-latest

    needs: [build]

    name: 'Tag ${{ matrix.VERSION }}'

    strategy:
      fail-fast: false
      matrix:
        VERSION: ${{ fromJSON(needs.build.outputs.imageTags) }}

    steps:
      -
        name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ matrix.VERSION }}',
              sha: context.sha
            })
    
  release:

    runs-on: ubuntu-latest

    needs: [build,tag]

    name: 'Release ${{ matrix.VERSION }}'

    strategy:
      fail-fast: false
      matrix:
        VERSION: ${{ fromJSON(needs.build.outputs.imageTags) }}

    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 'v${{ matrix.VERSION }}'
          release_name: 'Release ver. ${{ matrix.VERSION }}'
          draft: false
          prerelease: false