name: 'Master build'

on:
  push:
    branches:
      - 'main'

run-name: 'Master build #${{github.run_number}}'

env:
  NODE_VERSION: '18.12.1'

jobs:
  build:

    runs-on: ubuntu-latest

    outputs:
      imageTag: ${{ steps.nextVersion.outputs.nextVersion }}

    steps:
      - 
        name: Checkout the branch
        uses: actions/checkout@v3
      - 
        name: Get tags
        run: git fetch --tags origin
      - 
        name: Setup Node
        uses: actions/setup-node@v3

        with:
          node-version: ${{ env.NODE_VERSION }}
      - 
        name: Install Node modules
        run: cd app/ && npm install
      - 
        name: Test
        run: cd app/ && npm test
      - 
        name: Determine next version number
        id: nextVersion
        uses: newsome-solutions-ltd/release-version-action@main
        with:
          versionScheme: 'x'

  tag:

    runs-on: ubuntu-latest

    needs: [build]

    steps:
      -
        name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ needs.build.outputs.imageTag }}',
              sha: context.sha
            })
    
  release:

    runs-on: ubuntu-latest

    needs: [build,tag]

    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 'v${{ needs.build.outputs.imageTag }}'
          release_name: 'Release ver. ${{ needs.build.outputs.imageTag }}'
          draft: false
          prerelease: false